### ISSUE TITLE
Why do you write this WAF?

### ISSUE THREAD

**Issue by gitmko0** [asalih/guardian#14]
1. Why do you write this WAF? 
2. What does it solve?

**Comment by asalih** [comment]
1. Guardian can work with mod security rule syntax, kind of re-written with Go but its working like waf as a service.
2. Besides of trying to protect a web application, you can also manage within one place your web applications instead of installing plugins to any server. Also you can be able to track any attacks and as next step it can be notify you about vulnerabilities on your web server.

**Comment by icf20** [comment]
@gitmko0 see this video https://youtu.be/TpRJD6MUV3g
